// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(FlashyLearnContext))]
    [Migration("20220820224210_RemovingFrequencyAsEntity")]
    partial class RemovingFrequencyAsEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.HasKey("CategoryID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Domain.Entities.FlashCard", b =>
                {
                    b.Property<Guid>("FlashCardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BackText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CategoryID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer");

                    b.Property<string>("FrontText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FlashCardID");

                    b.HasIndex("CategoryID");

                    b.ToTable("FlashCards");
                });

            modelBuilder.Entity("Domain.Entities.FlashCardTag", b =>
                {
                    b.Property<Guid>("TagID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FlashCardID")
                        .HasColumnType("uuid");

                    b.HasKey("TagID", "FlashCardID");

                    b.HasIndex("FlashCardID");

                    b.ToTable("FlashCardTags");
                });

            modelBuilder.Entity("Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("TagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TagID");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("FlashCardTag", b =>
                {
                    b.Property<Guid>("FlashCardsFlashCardID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagsTagID")
                        .HasColumnType("uuid");

                    b.HasKey("FlashCardsFlashCardID", "TagsTagID");

                    b.HasIndex("TagsTagID");

                    b.ToTable("FlashCardTag");
                });

            modelBuilder.Entity("Domain.Entities.FlashCard", b =>
                {
                    b.HasOne("Domain.Entities.Category", "Category")
                        .WithMany("FlashCards")
                        .HasForeignKey("CategoryID")
                        .IsRequired()
                        .HasConstraintName("FK_FlashCard_Category");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Entities.FlashCardTag", b =>
                {
                    b.HasOne("Domain.Entities.FlashCard", "FlashCard")
                        .WithMany("FlashCardTags")
                        .HasForeignKey("FlashCardID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Tag", "Tag")
                        .WithMany("FlashCardTags")
                        .HasForeignKey("TagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlashCard");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("FlashCardTag", b =>
                {
                    b.HasOne("Domain.Entities.FlashCard", null)
                        .WithMany()
                        .HasForeignKey("FlashCardsFlashCardID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsTagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Navigation("FlashCards");
                });

            modelBuilder.Entity("Domain.Entities.FlashCard", b =>
                {
                    b.Navigation("FlashCardTags");
                });

            modelBuilder.Entity("Domain.Entities.Tag", b =>
                {
                    b.Navigation("FlashCardTags");
                });
#pragma warning restore 612, 618
        }
    }
}
